; generated by Component: ARM Compiler 5.06 update 1 (build 61) Tool: ArmCC [4d35ad]
; commandline ArmCC [--c99 --split_sections --debug -c --asm -o.\objects\spi.o --depend=.\objects\spi.d --cpu=Cortex-M3 --apcs=interwork -O3 --diag_suppress=9931 -ID:\ele\STM\STM32F103\Projects\SPI_REG\RTE -ID:\ele\STM\STM32F103\Projects\SPI_REG\RTE\Device\STM32F103C8 -IC:\Keil_v5\ARM\PACK\ARM\CMSIS\4.5.0\CMSIS\Include -IC:\Keil_v5\ARM\PACK\Keil\STM32F1xx_DFP\2.0.0\Device\Include -D__UVISION_VERSION=518 -D_RTE_ -DSTM32F10X_MD --omf_browse=.\objects\spi.crf spi.c]
        THUMB
        REQUIRE8
        PRESERVE8

        AREA ||i.SpiInit||, CODE, READONLY, ALIGN=2

SpiInit PROC
        LDR      r1,|L1.68|
        PUSH     {r4,lr}
        MOV      r0,#0x1014
        STR      r0,[r1,#0x18]
        LDR      r4,|L1.72|
        MOVS     r2,#1
        MOVS     r1,#0x10
        MOV      r0,r4
        BL       GpioConfig
        MOVS     r2,#9
        MOVS     r1,#0x20
        MOV      r0,r4
        BL       GpioConfig
        MOVS     r2,#8
        MOVS     r1,#0x40
        MOV      r0,r4
        BL       GpioConfig
        MOVS     r2,#9
        MOVS     r1,#0x80
        MOV      r0,r4
        BL       GpioConfig
        BL       CS_HIGH
        LDR      r1,|L1.76|
        MOV      r0,#0x35c
        STRH     r0,[r1,#0]
        POP      {r4,pc}
        ENDP

        DCW      0x0000
|L1.68|
        DCD      0x40021000
|L1.72|
        DCD      0x40010800
|L1.76|
        DCD      0x40013000

        AREA ||i.SpiTransmit||, CODE, READONLY, ALIGN=2

SpiTransmit PROC
        PUSH     {r4,r5,lr}
        MOVS     r3,#0
        LDR      r2,|L2.40|
        LDR      r4,|L2.44|
        B        |L2.32|
|L2.10|
        LDRH     r5,[r2,#8]
        LSLS     r5,r5,#30
        BPL      |L2.10|
        STRH     r0,[r2,#0xc]
|L2.18|
        LDRH     r5,[r2,#8]
        LSLS     r5,r5,#31
        BEQ      |L2.18|
        LDRH     r5,[r2,#0xc]
        STRB     r5,[r4,r3]
        ADDS     r3,r3,#1
        UXTB     r3,r3
|L2.32|
        CMP      r3,r1
        BCC      |L2.10|
        LDRB     r0,[r4,#0]  ; SpiRxBuffer
        POP      {r4,r5,pc}
        ENDP

|L2.40|
        DCD      0x40013000
|L2.44|
        DCD      ||.data||

        AREA ||.arm_vfe_header||, DATA, READONLY, NOALLOC, ALIGN=2

        DCD      0x00000000

        AREA ||.data||, DATA, ALIGN=0

SpiRxBuffer
        DCB      0x01,0x02,0x03,0x04
        DCB      0x05,0x06

        AREA ||i.CS_HIGH||, COMGROUP=CS_HIGH, CODE, READONLY, ALIGN=2

CS_HIGH PROC
        LDR      r0,|L22.16|
|L22.2|
        LDRH     r1,[r0,#8]
        LSLS     r1,r1,#24
        BMI      |L22.2|
        LDR      r1,|L22.20|
        MOVS     r0,#0x10
        STR      r0,[r1,#0]
        BX       lr
        ENDP

|L22.16|
        DCD      0x40013000
|L22.20|
        DCD      0x40010810

        AREA ||i.CS_LOW||, COMGROUP=CS_LOW, CODE, READONLY, ALIGN=2

CS_LOW PROC
        LDR      r1,|L28.12|
        MOV      r0,#0x100000
        STR      r0,[r1,#0]
        BX       lr
        ENDP

        DCW      0x0000
|L28.12|
        DCD      0x40010810

;*** Start embedded assembler ***

#line 1 "spi.c"
	AREA ||.rev16_text||, CODE
	THUMB
	EXPORT |__asm___5_spi_c_c3e2863e____REV16|
#line 388 "C:\\Keil_v5\\ARM\\PACK\\ARM\\CMSIS\\4.5.0\\CMSIS\\Include\\cmsis_armcc.h"
|__asm___5_spi_c_c3e2863e____REV16| PROC
#line 389

 rev16 r0, r0
 bx lr
	ENDP
	AREA ||.revsh_text||, CODE
	THUMB
	EXPORT |__asm___5_spi_c_c3e2863e____REVSH|
#line 402
|__asm___5_spi_c_c3e2863e____REVSH| PROC
#line 403

 revsh r0, r0
 bx lr
	ENDP
	AREA ||.rrx_text||, CODE
	THUMB
	EXPORT |__asm___5_spi_c_c3e2863e____RRX|
#line 587
|__asm___5_spi_c_c3e2863e____RRX| PROC
#line 588

 rrx r0, r0
 bx lr
	ENDP

;*** End   embedded assembler ***

        EXPORT SpiInit [CODE]
        EXPORT SpiTransmit [CODE]
        EXPORT SpiRxBuffer [DATA,SIZE=6]
        EXPORT CS_HIGH [CODE]
        EXPORT CS_LOW [CODE]

        IMPORT ||Lib$$Request$$armlib|| [CODE,WEAK]
        IMPORT GpioConfig [CODE]

        ATTR FILESCOPE
        ATTR SETVALUE Tag_ABI_PCS_wchar_t,2
        ATTR SETVALUE Tag_ABI_enum_size,1
        ATTR SETVALUE Tag_ABI_optimization_goals,3
        ATTR SETSTRING Tag_conformance,"2.06"
        ATTR SETVALUE AV,18,1

        ASSERT {ENDIAN} = "little"
        ASSERT {INTER} = {TRUE}
        ASSERT {ROPI} = {FALSE}
        ASSERT {RWPI} = {FALSE}
        ASSERT {IEEE_FULL} = {FALSE}
        ASSERT {IEEE_PART} = {FALSE}
        ASSERT {IEEE_JAVA} = {FALSE}
        END
